# SwiftLint Configuration for MetalHead

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - identifier_name

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Custom rules
custom_rules:
  metalhead_naming:
    name: "MetalHead Naming Convention"
    regex: '^[A-Z][a-zA-Z0-9]*$'
    match_kinds:
      - identifier
    message: "Class and struct names should use PascalCase"
    
  metalhead_private_members:
    name: "Private Members Convention"
    regex: '^_[a-z][a-zA-Z0-9]*$'
    match_kinds:
      - identifier
    message: "Private members should start with underscore and use camelCase"

# File header
file_header:
  required_pattern: |
                    \/\/
                    \/\/  MetalHead
                    \/\/  .*
                    \/\/  .*
                    \/\/  Created by .* on .*
                    \/\/

# Line length
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# File length
file_length:
  warning: 500
  error: 1000

# Type body length
type_body_length:
  warning: 300
  error: 500

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - uri
    - api
    - ui
    - id
    - url
    - uri
    - api
    - ui

# Force unwrapping
force_unwrapping:
  severity: warning

# Implicit return
implicit_return:
  severity: warning

# Operator usage whitespace
operator_usage_whitespace:
  severity: warning

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true

# Force try
force_try:
  severity: warning

# Force cast
force_cast:
  severity: warning

# Unused closure parameter
unused_closure_parameter:
  severity: warning

# Unused optional binding
unused_optional_binding:
  severity: warning

# Unused import
unused_import:
  severity: warning

# Unused declaration
unused_declaration:
  severity: warning

# Explicit self
explicit_self:
  severity: warning

# Explicit init
explicit_init:
  severity: warning

# Empty count
empty_count:
  severity: warning

# Empty string
empty_string:
  severity: warning

# Fallthrough
fallthrough:
  severity: warning

# Fatal error message
fatal_error_message:
  severity: warning

# Force unwrapping
force_unwrapping:
  severity: warning

# Implicit return
implicit_return:
  severity: warning

# Operator usage whitespace
operator_usage_whitespace:
  severity: warning

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true

# Force try
force_try:
  severity: warning

# Force cast
force_cast:
  severity: warning

# Unused closure parameter
unused_closure_parameter:
  severity: warning

# Unused optional binding
unused_optional_binding:
  severity: warning

# Unused import
unused_import:
  severity: warning

# Unused declaration
unused_declaration:
  severity: warning

# Explicit self
explicit_self:
  severity: warning

# Explicit init
explicit_init:
  severity: warning

# Empty count
empty_count:
  severity: warning

# Empty string
empty_string:
  severity: warning

# Fallthrough
fallthrough:
  severity: warning

# Fatal error message
fatal_error_message:
  severity: warning
